// Code generated by "stringer -type=busPacketType"; DO NOT EDIT.

package ibusnats

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[busPacketResponse-0]
	_ = x[busPacketClose-1]
	_ = x[busPacketSectionMap-2]
	_ = x[busPacketSectionArray-3]
	_ = x[busPacketSectionObject-4]
	_ = x[busPacketSectionElement-5]
	_ = x[busPacketMiscInboxName-6]
}

const _busPacketType_name = "busPacketResponsebusPacketClosebusPacketSectionMapbusPacketSectionArraybusPacketSectionObjectbusPacketSectionElementbusPacketMiscInboxName"

var _busPacketType_index = [...]uint8{0, 17, 31, 50, 71, 93, 116, 138}

func (i busPacketType) String() string {
	if i >= busPacketType(len(_busPacketType_index)-1) {
		return "busPacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _busPacketType_name[_busPacketType_index[i]:_busPacketType_index[i+1]]
}
