version: '3.3'

services:
  nats1:
    image: nats:2.0.2
    deploy:
      placement:
        constraints:
          - node.hostname==untill-test-01
    command:
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://0.0.0.0:6222"
      - "-routes"
      - "nats://nats2:6222,nats://nats3:6222"
    networks:
      - webgateway

  nats2:
    image: nats:2.0.2
    deploy:
      placement:
        constraints:
          - node.hostname==untill-test-02
    command:
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://0.0.0.0:6222"
      - "-routes"
      - "nats://nats1:6222,nats://nats3:6222"
    networks:
      - webgateway

  nats3:
    image: nats:2.0.2
    deploy:
      placement:
        constraints:
          - node.hostname==untill-test-03
    command:
      - "-p"
      - "4222"
      - "-cluster"
      - "nats://0.0.0.0:6222"
      - "-routes"
      - "nats://nats1:6222,nats://nats2:6222"
    networks:
      - webgateway

networks:
  webgateway:
    external: true
